package engine2d.events;

public enum EventType {
    NOEVENT,
    WINDOWCLOSED, WINDOWRESIZED, WINDOWMOVED, WINDOWFOCUSED,
    KEYPRESSED, KEYRELEASED,
    MOUSEBUTTONPRESSED, MOUSEBUTTONRELEASED, MOUSEMOVED, MOUSESCROLLED
}
