package engine2D.events;

public enum EventType {

    NOEVENT,
    WINDOWCLOSED, WINDOWRESIZED, WINDOWMOVED, WINDOWFOCUSED,
    KEYPRESSED, KEYRELEASED,
    MOUSEBUTTONPRESSED, MOUSEBUTTONRELEASED, MOUSEMOVED, MOUSESCROLLED,
    CURRENTCAMERACHANGED

}
